const XLSX = require('xlsx');
const PDFDocument = require('pdfkit');

// Helper to escape values for CSV
function escapeCSVValue(val) {
  if (val === null || val === undefined) return '';
  const str = String(val);
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

// Generate CSV string buffer
function generateCSV(data, headers, reportTitle, generatedBy, filtersText, locationsText, deptsText) {
  const csvLines = [];
  
  // 1. Professional Headers (Metadata)
  csvLines.push(`PGP Glass Apprentice Portal`);
  csvLines.push(`Report Name,${escapeCSVValue(reportTitle)}`);
  csvLines.push(`Generated By,${escapeCSVValue(generatedBy)}`);
  csvLines.push(`Generated Date & Time,${escapeCSVValue(new Date().toLocaleString())}`);
  csvLines.push(`Report Format,CSV`);
  csvLines.push(`Applied Filters,${escapeCSVValue(filtersText || 'None')}`);
  csvLines.push(`Locations Included,${escapeCSVValue(locationsText || 'All')}`);
  csvLines.push(`Departments Included,${escapeCSVValue(deptsText || 'All')}`);
  csvLines.push(`Total Records,${data.length}`);
  csvLines.push(''); // spacing line
  
  // 2. Data Header row
  csvLines.push(headers.map(h => escapeCSVValue(h)).join(','));
  
  // 3. Data Rows
  data.forEach(row => {
    const rowValues = headers.map(header => {
      // Resolve mapped or dynamic properties
      const val = row[header];
      return escapeCSVValue(val !== undefined ? val : '');
    });
    csvLines.push(rowValues.join(','));
  });
  
  return Buffer.from(csvLines.join('\n'), 'utf-8');
}

// Generate Excel (.xlsx) buffer
function generateExcel(data, headers, reportTitle, generatedBy, filtersText, locationsText, deptsText) {
  const rows = [];
  
  // 1. Professional Header rows
  rows.push(["PGP Glass Apprentice Portal"]);
  rows.push(["Report Name", reportTitle]);
  rows.push(["Generated By", generatedBy]);
  rows.push(["Generated Date & Time", new Date().toLocaleString()]);
  rows.push(["Report Format", "Excel (.xlsx)"]);
  rows.push(["Applied Filters", filtersText || "None"]);
  rows.push(["Locations Included", locationsText || "All"]);
  rows.push(["Departments Included", deptsText || "All"]);
  rows.push(["Total Records", data.length]);
  rows.push([]); // spacing row
  
  // 2. Column Headers
  rows.push(headers);
  
  // 3. Data Rows
  data.forEach(row => {
    const rowValues = headers.map(header => {
      const val = row[header];
      return val !== undefined ? val : '';
    });
    rows.push(rowValues);
  });
  
  // 4. Create Workbook & Worksheet
  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.aoa_to_sheet(rows);
  
  // 5. Calculate auto column widths (starting from row index 10 - the header row)
  const wscols = [];
  headers.forEach((header, colIdx) => {
    let maxLength = String(header).length;
    for (let r = 10; r < rows.length; r++) {
      const val = rows[r][colIdx];
      if (val !== undefined && val !== null) {
        maxLength = Math.max(maxLength, String(val).length);
      }
    }
    wscols.push({ wch: maxLength + 3 }); // add padding
  });
  ws['!cols'] = wscols;
  
  XLSX.utils.book_append_sheet(wb, ws, "Apprentice Report");
  
  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}

// Generate PDF buffer
function generatePDF(data, headers, reportTitle, generatedBy, filtersText, locationsText, deptsText) {
  return new Promise((resolve, reject) => {
    try {
      // Landscape A4: 842 x 595. Available width with margins (30 each) is 782
      const doc = new PDFDocument({ layout: 'landscape', size: 'A4', margin: 30 });
      const chunks = [];
      
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', err => reject(err));
      
      // Page styling helper
      let pageNum = 0;
      doc.on('pageAdded', () => {
        pageNum++;
        drawFooter(doc, pageNum);
      });
      
      // Draw footer helper
      function drawFooter(pdfDoc, pageNo) {
        pdfDoc.save();
        
        // Temporarily set bottom margin to 0 during footer drawing to prevent recursive page breaks
        const oldBottomMargin = pdfDoc.page.margins.bottom;
        pdfDoc.page.margins.bottom = 0;
        
        pdfDoc.strokeColor('#cbd5e1').lineWidth(0.5);
        pdfDoc.moveTo(30, 560).lineTo(812, 560).stroke();
        
        pdfDoc.fillColor('#94a3b8').fontSize(8);
        pdfDoc.text("PGP Glass Apprentice Portal — Confidential Report", 30, 568, { lineBreak: false });
        pdfDoc.text(`Page ${pageNo}`, 760, 568, { align: 'right', width: 52, lineBreak: false });
        
        pdfDoc.page.margins.bottom = oldBottomMargin;
        pdfDoc.restore();
      }
      
      // Page 1 footer setup (manually increment pageNum and draw first footer)
      pageNum++;
      drawFooter(doc, pageNum);
      
      // Header and Logo styling
      doc.fillColor('#0f172a').fontSize(22).font('Helvetica-Bold').text("PGP Glass Apprentice Portal", 30, 30);
      doc.fillColor('#2563eb').fontSize(14).font('Helvetica-Bold').text(reportTitle, 30, 56);
      
      doc.strokeColor('#e2e8f0').lineWidth(1);
      doc.moveTo(30, 75).lineTo(812, 75).stroke();
      
      // Metadata Grid Layout
      doc.fillColor('#1e293b').fontSize(9).font('Helvetica-Bold').text("Report Metadata:", 30, 85);
      doc.font('Helvetica');
      doc.fillColor('#475569');
      
      // Col 1
      doc.text(`Generated By: ${generatedBy}`, 30, 100);
      doc.text(`Generated Date: ${new Date().toLocaleString()}`, 30, 114);
      doc.text(`Report Format: PDF (A4 Landscape)`, 30, 128);
      
      // Col 2
      doc.text(`Locations: ${locationsText || 'All'}`, 240, 100);
      doc.text(`Departments: ${deptsText || 'All'}`, 240, 114);
      doc.text(`Total Records: ${data.length}`, 240, 128);
      
      // Col 3 (Applied Filters box)
      doc.rect(460, 85, 352, 55).fill('#f8fafc').stroke('#cbd5e1');
      doc.fillColor('#0f172a').font('Helvetica-Bold').text("Active Filters Applied", 470, 92);
      doc.font('Helvetica').fillColor('#475569').fontSize(8);
      doc.text(filtersText || "No custom filters applied. All active/completed entries included.", 470, 106, { width: 330, height: 30 });
      
      // Draw grid outline for table header
      let startY = 160;
      doc.fontSize(9);
      
      // Select columns to display in PDF
      // If we have standard employee columns (e.g. Employee Code), we display a custom subset of headers that fit cleanly.
      // If it's a summary count report (e.g. Branch Wise), we show its exact columns.
      let displayHeaders = [...headers];
      let colWidths = [];
      let isRecordsTable = false;
      
      if (headers.includes("Employee Code")) {
        isRecordsTable = true;
        // Limit PDF grid to top 9 most important columns to ensure readability
        displayHeaders = ["Employee Code", "Full Name", "Location", "Department", "Joining Date", "Record Status", "Employee Contract ID", "Portal Enrollment Number", "Portal Name"];
        // Available width = 782.
        colWidths = [65, 120, 70, 85, 65, 55, 105, 120, 97];
      } else {
        // Summary Report: distribute width evenly
        const widthPerCol = Math.floor(782 / headers.length);
        headers.forEach(() => colWidths.push(widthPerCol));
      }
      
      // Draw table headers
      doc.rect(30, startY, 782, 22).fill('#1e293b');
      doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(8.5);
      
      let curX = 30;
      displayHeaders.forEach((header, idx) => {
        doc.text(header, curX + 5, startY + 6, { width: colWidths[idx] - 10, lineBreak: false });
        curX += colWidths[idx];
      });
      
      // Draw rows
      let curY = startY + 22;
      doc.font('Helvetica').fontSize(8).fillColor('#334155');
      
      data.forEach((row, rowIdx) => {
        // Check page break: A4 landscape height is 595. Margin bottom is 50.
        if (curY > 520) {
          doc.addPage();
          // Draw table header again on new page
          doc.rect(30, 40, 782, 22).fill('#1e293b');
          doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(8.5);
          
          let headerX = 30;
          displayHeaders.forEach((header, idx) => {
            doc.text(header, headerX + 5, 46, { width: colWidths[idx] - 10, lineBreak: false });
            headerX += colWidths[idx];
          });
          
          curY = 62;
          doc.font('Helvetica').fontSize(8).fillColor('#334155');
        }
        
        // Alternating row background
        if (rowIdx % 2 === 1) {
          doc.rect(30, curY, 782, 20).fill('#f8fafc');
        }
        
        // Draw cell text
        let rowX = 30;
        doc.fillColor('#334155');
        
        displayHeaders.forEach((header, colIdx) => {
          let val = row[header];
          if (val === undefined || val === null) val = '';
          doc.text(String(val), rowX + 5, curY + 6, { width: colWidths[colIdx] - 10, height: 14, lineBreak: false });
          rowX += colWidths[colIdx];
        });
        
        // Draw bottom row divider line
        doc.strokeColor('#cbd5e1').lineWidth(0.5);
        doc.moveTo(30, curY + 20).lineTo(812, curY + 20).stroke();
        
        curY += 20;
      });
      
      if (isRecordsTable && headers.length > displayHeaders.length) {
        // Render a note about missing dynamic fields
        curY += 10;
        doc.fillColor('#64748b').fontSize(8.5).font('Helvetica-Oblique');
        doc.text("* Note: Dynamic/imported columns and full complete completion remark fields are omitted in PDF grid for print alignment. Use Excel/CSV for complete master data exports.", 30, curY, { width: 782 });
      }
      
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = {
  generateCSV,
  generateExcel,
  generatePDF
};
